#!/bin/bash

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
mkdir -p "$config_home"

set -x

mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/vim/vimrc"              "$HOME/.vimrc"
ln -sf "$PWD/vim/vim-plug/plug.vim"  "$HOME/.vim/autoload/plug.vim"

rm -rf "$config_home/alacritty"
ln -sf "$PWD/alacritty" "$config_home/alacritty"

ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"
