#!/bin/bash
set -euo pipefail

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
mkdir -p "$config_home"

set -x

# vim
mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/vim/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/vim/vim-plug/plug.vim" "$HOME/.vim/autoload/plug.vim"
# alacritty
rm -rf "$config_home/alacritty"
ln -sf "$PWD/alacritty" "$config_home/alacritty"
# tmux
ln -sf "$PWD/tmux/tmux.conf" "$HOME/.tmux.conf"
# git
erb "$PWD/git/gitconfig.erb" > "$PWD/git/gitconfig"
ln -sf "$PWD/git/gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/git/gitignore_global" "$HOME/.gitignore_global"
# zsh
ln -sf "$PWD/zsh/zshrc" "$HOME/.zshrc"
ln -sf "$PWD/zsh/zshenv" "$HOME/.zshenv"
