#!/bin/sh

userresources="$XDG_CONFIG_HOME/x/Xresources"
usermodmap="$XDG_CONFIG_HOME/x/Xmodmap"
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"

# merge in defaults and keymaps
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# load system xinit scripts
if -d [ /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
fi

# set wallpaper
hsetroot -root -cover ~/pix/wallpapers/wallpaper
# make capslock behave as control (when held), and right alt behave as compose
kbdremap
# notifications
dunst &
# flux
fluxgui &
# network manager applet
nm-applet &
# screen locker
xss-lock --transfer-sleep-lock -- ~/.local/bin/betterlockscreen -l &
# keep awake if needed
caffeine-indicator &
# dwm status script
~/.local/bin/status &
# hotkeys (separate these from dwm as much as possible)
sxhkd &
# compositor
picom &

# start wm
exec dwm

