#!/bin/sh

# set wallpaper
hsetroot -root -cover ~/pix/wallpapers/wallpaper
# load .Xresources
xrdb ~/.config/xresources/Xresources
# make capslock behave as control (when held), and right alt behave as compose
kbdremap
# notifications
dunst &
# flux
fluxgui &
# network manager applet
nm-applet &
# screen locker
xss-lock --transfer-sleep-lock -- ~/.local/bin/betterlockscreen -l &
# keep awake if needed
caffeine-indicator &
# dwm status script
~/.local/bin/status &
# hotkeys (separate these from dwm as much as possible)
sxhkd &
# compositor
picom &

# start wm
exec dwm

